# aws_region = "ap-south-1"
# environment = "dev"
# project_name = "eks-platform"
# cluster_name = "platform-eks"
# vpc_cidr = "10.0.0.0/16"

# backend_bucket = "my-tf-state-bucket"
# backend_key = "eks/dev/terraform.tfstate"
# backend_region = "ap-south-1"
# backend_dynamodb_table = "terraform-locks"
